### ISSUE TITLE
Interpolation options ?

### ISSUE THREAD

**Issue by meutzitzu** [bojidar-bg/plasma-parallax-wallpaper#1]
I've begun using it and I've noticed while on slow desktop sliding speeds it does achieve the desired effect, I like high desktop switching speeds, and for those the animation doesn't quite match up. No amount of tweaking the slide duration seems to make the parralax believable for me. I think it has something to do with the interpolation. while this plug-in definitley seems to me like it's using linear interpolation, I'm pretty sure the Plasma desktop uses some kind of Bezier ease-in&ease-out interp. 

Would be nice if there were 2 extra parameters: ease-in and ease-out coefficients. 0 means no tangency at that end, so, effectively linear, and higher values mean greater easing near the ends of the animation.

**Comment by bojidar-bg** [comment]
Apparently, Plasma uses OutCubic easing https://phabricator.kde.org/source/kwin/browse/master/effects/slide/slide.cpp$37. I'll look into switching to that.
