### ISSUE TITLE
system timeout

### ISSUE THREAD

**Issue by 1sra3l** [bojidar-bg/plasma-parallax-wallpaper#3]
Hi I saw [interval: 1000 // FIXME TODO: Use platform value for tooltip activation delay.](https://github.com/bojidar-bg/plasma-parallax-wallpaper/blob/master/package/contents/ui/ConfigWallpaperDelegate.qml#L138)

And found this: [int KToolTipWidget::hideDelay ( ) const](https://api.kde.org/frameworks/kwidgetsaddons/html/classKToolTipWidget.html#ab80cf2463a8a1cd7ef57ecb547c8fddb) the default is apparently 500 (or 5000 see below)

Though looking at [Plasma Frameworks Tooltip](https://api.kde.org/frameworks/plasma-framework/html/ToolTip_8qml_source.html) I see `timeout: 5000` is the default for Plasma Tooltips.

I have not used QML in years, though I can still read it, and I have never used KDE's C++ frameworks, so I cannot give any actual PR.  I do hope that info helps you get the effect you want

**Comment by bojidar-bg** [comment]
Hey, that code comes from Zren's awesome Animated Hue plugin: [upstream source](https://github.com/Zren/plasma-wallpapers/blob/8204f878b795575d28ce43737de0f46a0a05b33e/animatedhue/package/contents/ui/WallpaperDelegate.qml#L154). If you plan on making a PR, it might be prudent to open it on his repo first.

The ideal solution here would be not having to implement `ConfigWallpaperDelegate` and `ConfigImagePicker`, but use some readily-available components for those instead; sadly my QML knowledge is not that good either.

Thanks for taking the effort to investigate the issue!

**Comment by 1sra3l** [comment]
Ok I posted the issue there!
