### ISSUE TITLE
Incompatible with Plasma 5.26?

### ISSUE THREAD

**Issue by armakunizen** [bojidar-bg/plasma-parallax-wallpaper#4]
It looks like this plugin doesn't work with Plasma 5.26.

There are only options in configuration dialog for the parallax settings, but no wallpaper selection.

**Comment by bojidar-bg** [comment]
Yeaa... noticed it a few days ago myself when trying to set it up on a new machine. The wallpaper settings dialogue was copied off the hue-rotate wallpaper plugin, but apparently it's stopped working now. 

Bit busy right now, but will try to get to it in a week or two.

**Comment by nomasteryoda** [comment]
Did you get some free time? 
I'm seeing a similar issue on my current ArchLinux installation.  Parallax does not show any images to choose from or any indication of the controls to select wallpaper. ON a plus note, the plugin works for color selection.

**Comment by bojidar-bg** [comment]
Okay, pushed a fix to master, but the store page is temporarily down right now, so it might be a bit before I upload the new version.
