### ISSUE TITLE
KDE Plasma 6 Update

### ISSUE THREAD

**Issue by jb2170** [bojidar-bg/plasma-parallax-wallpaper#6]
Hi,
I've been using this wallpaper plugin for a while now on Arch Linux, it worked beautifully! But now KDE 6 is out and the plugin no longer shows as available on the store / is no longer selectable in KDE settings. (I logged in to a black background after updating 😅)
Does the plugin need updating or is it something on my end?
Thanks

**Comment by bojidar-bg** [comment]
Hm.. odd, it works fine for me, also on Arch Linux, it's just not in the store :joy: 

Made a new store listing as a Plasma 6 extension at https://store.kde.org/p/2135733/, can you confirm it works for you? (:

**Comment by jb2170** [comment]
Thanks for the reply!

It seems there's some deprecations from Plasma 5 -> 6.

The plugin now shows on the store, but doesn't work fully. When installed from the store it goes into
`~/.local/usr/share/plasma/wallpapers/$RANDOM_STRING` instead of
`~/.local/usr/share/plasma/wallpapers/com.github.bojidar-bg.parallax` and does not show up in Settings/Wallpaper
I had a compare with the other two wallpapers on the store for Plasma 6, and they're a bit buggy too

I've made some commits on a [forked branch][fork], with links to the KDE documentation on a couple of Plasma 6 deprecations in the commit messages; `.desktop` for the metadata file is now obsolete and a [few tweaks][few-tweaks] have to be made to `metadata.json`. With these tweaks the plugin shows in Settings/Wallpaper, and I would guess it installs to the correct folder?

Next, the wallpaper image selector does not show in the settings menu 
![image](https://github.com/bojidar-bg/plasma-parallax-wallpaper/assets/66702639/19e3b256-10bd-4078-a5cf-c4ce1665a096)

Checking the journal with `journalctl --user -f -n 0 --output cat` I see

```txt
QQmlComponent: Component is not ready
qrc:/kcm/kcm_wallpaper/main.qml:111:9: QML StackView: replace: file:///home/jb2170/.local/usr/share/plasma/wallpapers/com.github.bojidar-bg.parallax/contents/ui/config.qml:22 module "QtQuick.Controls" version 1.0 is not installed
```

I've never done Qt / QML before so this is where I'm stuck :sweat_smile: . Perhaps there's some changes in libraries like [Qt Quick Controls][qtquickcontrols]? If I naively change some version numbers from `1.x` to `6.0` the error messages progress from version errors to semantic errors, but they're about QML libraries which I'm not familiar with.

[fork]: https://github.com/jb2170/plasma-parallax-wallpaper/commits/plasma-6-fix/
[few-tweaks]: https://github.com/jb2170/plasma-parallax-wallpaper/commit/3354cc3d7e9203115b08230d70c9e8fbabb96884
[qtquickcontrols]: https://doc.qt.io/qt-6/qtquickcontrols-index.html

**Comment by bojidar-bg** [comment]
Hm... I actually based much of the config QML files off of https://github.com/Zren/plasma-wallpapers/blob/master/animatedhue/package/contents/ui/config.qml – which has already caused some troubles in the past :sweat_smile:

Perhaps it would be smarter to base the config off of https://invent.kde.org/plasma/plasma-workspace/-/blob/master/wallpapers/image/imagepackage/contents/ui/config.qml instead; in fact, I would much enjoy being able to directly include that file and stretch the default imagepackge's main.qml :thinking: 

I'll try to get my local Arch installation fully updated and see if the settings break for me too (:

**Comment by bojidar-bg** [comment]
Mmm... yep, you are right, it's all broken under Plasma 6 :sweat_smile: I'll branch off your fork, fix whatever stuff is going on in the QML, and push to master, if that's alright with you? (:

**Comment by bojidar-bg** [comment]
..Nevermind the question, I went ahead and did just that. Enjoy the update, and thanks for the initial push! :blush: 

Closing as it \*should\* be all fixed now.

**Comment by jb2170** [comment]
That fixed it! Installs + works perfectly. Thank you very much for the quick replies + fix :smile:
